name: PHPUnit

on: push

jobs:
  phpunit:
    runs-on: ubuntu-22.04
    continue-on-error: ${{ matrix.php == 'nightly' }}

    strategy:
      matrix:
        php: [7.1, 7.2, 7.3, 7.4, 8.0]
        stability: [--prefer-lowest, --prefer-stable]
        include:
          - php: nightly
            stability: --prefer-lowest
          - php: nightly
            stability: --prefer-stable

    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install PHPUnit 7
        id: phpunit-7
        if: ${{ matrix.php == '7.1' || matrix.php == '7.2' }}
        run: composer require phpunit/phpunit:^7 --no-interaction --no-update

      - name: Install PHPUnit 9
        if: ${{ steps.phpunit-7.outcome == 'skipped' }}
        run: composer require phpunit/phpunit:^9.5 --no-interaction --no-update

      - run: composer update ${{ matrix.stability }} --prefer-dist --no-interaction

      - run: ./vendor/bin/phpunit
